// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmRipjauqE3mH2GZGstRIoUIhnPY_bSrA',
    appId: '1:644724658131:web:074e9dac2967c1a2902926',
    messagingSenderId: '644724658131',
    projectId: 'courses-94387',
    authDomain: 'courses-94387.firebaseapp.com',
    storageBucket: 'courses-94387.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMIYcgA3uU1dp6hQxiCTFhJKyVvKIfMR8',
    appId: '1:644724658131:android:72e1ba9af1349f24902926',
    messagingSenderId: '644724658131',
    projectId: 'courses-94387',
    storageBucket: 'courses-94387.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6SH0-m02oethRd46ybP15yg8JSLnbSCI',
    appId: '1:644724658131:ios:8d095da062ee79a5902926',
    messagingSenderId: '644724658131',
    projectId: 'courses-94387',
    storageBucket: 'courses-94387.appspot.com',
    iosClientId: '644724658131-hg1b0ivdeeptqj2fl06budhesssib8ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6SH0-m02oethRd46ybP15yg8JSLnbSCI',
    appId: '1:644724658131:ios:3b09d65024d90c8d902926',
    messagingSenderId: '644724658131',
    projectId: 'courses-94387',
    storageBucket: 'courses-94387.appspot.com',
    iosClientId: '644724658131-es0ae0e7ls1j7s00rmrbon5obdffhqq0.apps.googleusercontent.com',
    iosBundleId: 'com.example.courseApp.RunnerTests',
  );
}
